services:
  app:
    build: .
    container_name: dockit-cursor
    ports:
      - "3000:3000"
    #TODO: commented out for production
    # env_file:
    #   - .env
    restart: unless-stopped
    #TODO: remove everything here
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev