services:
  app:
    build: .
    container_name: dockit
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    #TODO: remove everything here
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev